name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v4.1.7
        with:
          persist-credentials: false

      - name: shellcheck all scripts
        run: |
          shellcheck --version
          find . -name '*.sh' -not -path './.git/*' -print0 | xargs -0 shellcheck
