name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.7
        with:
          persist-credentials: false

      - name: shellcheck all scripts
        run: |
          shellcheck --version
          find . -name '*.sh' -not -path './.git/*' -print0 | xargs -0 shellcheck
